# VelocityShield Configuration
# A powerful VPN detection plugin for Velocity proxy servers
# Documentation: https://github.com/jackh54/velocityshield

# API Configuration
# Get your API key at https://proxycheck.io/
proxycheck-api-key: "YOUR_PROXYCHECK_API_KEY"

# Message shown to players when they are kicked for using a VPN
# Supports MiniMessage text formatting (<red>, <bold>, etc.)
kick-message:
  title: "<red><bold>VPN Detected!</bold></red>"
  message: |
    <white>Please join without a VPN.</white>
    <white>If this is a false positive, please open a ticket.</white>

# VPN Detection Settings
# ---------------------
# Primary service to use for VPN detection
use-proxycheck-as-primary: true

# If primary service fails, try the other service
enable-fallback-service: true

# Allow players to join if both services fail (e.g., API limit reached)
allow-join-on-api-failure: true

# Cache Settings
# -------------
# Enable caching to reduce API requests
enable-cache: true

# How long to keep IP check results in cache
cache-duration: 10

# Time unit for cache duration
cache-time-unit: "SECONDS"  # Options: SECONDS, MINUTES, HOURS, DAYS

# Debug Settings
# -------------
# Enable detailed logging for troubleshooting
enable-debug: false

# Do not modify this
config-version: 1.1